language: C
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev
before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone -b als https://github.com/X00PD/android_kernel_asus_msm8937.git kernel
  - cd $HOME && git clone https://github.com/iamsaalim/kernel_script build_kernel
  - cp $HOME/build_kernel/build.sh $HOME/kernel/build.sh
  - cd $HOME/kernel && chmod +x build.sh
  - |
    cd $HOME/kernel
    source build.sh
    make -j4 O=out
  - cp $HOME/build_kernel/strip.sh $HOME/kernel/strip.sh
  - cd $HOME/kernel && chmod +x strip.sh && source strip.sh
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: $HOME/kernel/AnyKernel3/*.zip
  on:
    tags: false
    repo: iamsaalim/kernel_script
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
