version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev
           git clone https://github.com/iamsaalim/kernel_script kernel
           cd kernel
           source build.sh
           source strip.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
